### ISSUE TITLE
Mobile Checkin

### ISSUE THREAD

**Issue by dagentooboy** [jeffpiazza/derbynet#244] opened 2023-01-27 19:33 UTC
I am trying to get the mobile checkin to work for our race this weekend and I can only get it to recognize the barcodes if I use the much larger car tag printable. Once I do get it to scan it doesn't seem to take pictures and if I get really lucky and get it to take a picture it doesn't seem to pair it to that racer/car. I have been looking into how difficult it would be to port the normal check-in photo code to the mobile version but I haven't made it very far.

**Comment by dagentooboy** [comment] 2023-01-28 05:02
Actually for some reason car photos seem to work but not racer photos.

**Comment by sarmier** [comment] 2023-03-06 19:13
> 
We just ran our derby this last weekend and ran into the same problem with racer/car photos. The racer photos didn't really load to the database after taking their pictures with our iPad or Samsung Galaxy. The car photos worked pretty well.

**Comment by jeffpiazza** [comment] 2023-03-07 03:25
sarmier, what build were you running (from the About page)?

Any chance you have server logs (apache logs) exhibiting the issue?

**Comment by sarmier** [comment] 2023-03-07 05:32
Thanks Jeff. Here the info from the About Page: 
DerbyNet Revision
This is revision 1597, built on February 4 2023.
(a4d37c1f61e5f784dc59dd2655391352e8b31f93)

I'll email you the logs.

**Comment by TheTinkeringIdiot** [comment] 2023-09-15 20:58
I ran into this issue as well (car photo usually works but the racer photo doesn't) specifically on mobile check-in.

For me, it appears to be a combination of small SBC CPU, large upload photo size, and face detection during the photo upload. 

Server: Libre AML-S905X-CC (basically a RPi3) running DerbyNet revision 1634, built August 17 2023 (from About page)

Capture device: Firefox on iPhone14 (which captures gigantic photos)

On capturing any racer image, htop shows the server CPU going to 100% for a 5-30 seconds. If that goes on for the full 30 seconds, it trips PHP's default max_execution_time and the Nginx error.log shows:

> 2023/09/15 20:42:10 [error] 14222#14222: *262 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/derbynet/inc/facedetection.inc on line 129" while reading response header from upstream, client: 192.168.1.216, server: _, request: "POST /derbynet/action.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "192.168.1.79", referrer: "https://192.168.1.79/derbynet/mcheckin.php"

After which the racer photo does not appear on the bottom of the mobile check-in page, and the browser usually throws a few ajax error alerts. 

If I take a racer photo that's definitely not a face, or the face isn't very clear, this happens every attempt (almost - it will rarely still work). However it also happens sometimes with a clear face in the frame. Even when it does work, there's still a short (5-20 seconds) wait for the photo to appear on the check-in page.

**Comment by jeffpiazza** [comment] 2023-09-17 13:53
Oh!  Thank you, this explains a lot!

As you've probably surmised, the photo capture for the racer photo sets auto-cropping on, which causes the server to try to identify the face and crop the photo.  This doesn't happen for car photo capture, and there's presently no option available to the user to turn off the feature for racer photos.  For whatever reason (still TBD), the autocropping seems to have to work a good bit harder for photos captured by phone.

In my own recent testing, I've also noticed some occasions of the barcode reader incorrectly deciding it's found a barcode; this leads to some "no such racer" and similar messages.

**Comment by TheTinkeringIdiot** [comment] 2023-09-17 17:22
In my case, the max_execution_time timeout seems to always happen during feature detection in the Harr cascade algorithm in `detect_face1()`. Harr cascade is obviously a O(all the N's) algorithm, but it's generally accepted as a good solution for face detection, especially on small machines without a lot of horsepower, so I hesitate to blame it. Also, the image is being downscaled to 320x240 before the Harr cascade even begins, so that wouldn't explain why this happens in mobile check-in (phone camera) but not "desktop" check-in (with a web cam). 

I wonder, could it be the downscaling? That's a non-trivial operation in any environment, and it might explain the difference in capture devices. Reasonably priced webcams generally run at 720p or 1080p, so input images might be 1920x1080. However my phone creates images at a resolution of 3024x4032 - a ~6x increase in the pixel count. Regardless of encoding, this is a substantially larger load for the downscaling operation to deal with. Could it be that, when limited to a single core of a little RPi CPU (as it is on mine), the downscaling is taking long enough that the Harr cascade hasn't got time to complete within PHP's 30 second time limit? 

I'm not really well-versed enough in PHP to confirm whether this is the case, or to suggest a solution if it is, but it it seems like it might fit the symptoms.

**Comment by jeffpiazza** [comment] 2023-10-29 22:50
I've been experimenting a good bit with this lately.

(1) The original complaint that barcodes weren't being read successfully.  I don't have a conclusive answer for that, but have two working theories/suspicions:
  (a) The barcodes read only when presented horizontally.  This is expected behavior, but isn't well explained.
  (b) This may also be, at least in part, a manifestation of #271, now fixed.

(2) For the "can't upload photos" issue, it appears that the autocrop feature (as transliterated into PHP) is more demanding computationally than I'd realized.  Performance appears to be worst if there ISN'T actually a face to find in the image.  On an RPi server, autocrop can exceed the max_execution_time, even with an inexpensive webcam.

(To TheTinkeringIdiot's suggestion, downscaling of the image happens in the phone, before uploading.  I don't think the camera specs of a high-end smartphone actually affect the problem.)

I'm working on a substantial update of the mobile check-in page, hopefully to be ready within a few weeks.

**Comment by jeffpiazza** [comment] 2023-12-11 03:10
Even though this issue has kind of meandered to discuss a few different issues encountered with the Mobile Check-In page, I left it open to continue to collect feedback.  With v9.0, Mobile Check-In has been materially rewritten, and should address the biggest complaints:

- There's a watermark showing how to orient a barcode to be recognized.
- Some of the printed barcodes were unrecognizable due to #271.
- There's a control to turn off autocropping if leaving it on is causing photo uploads to time out.  (Timing out is more likely if there's not actually a face in the photo.)

I'm going to close this issue, and ask any users who continue to experience problems with Mobile Check-In to please file new bug(s) as needed.

**Closed by jeffpiazza** 2023-12-11 03:10 UTC
