### ISSUE TITLE
Timer Web Interface

### ISSUE THREAD

**Issue by jaeaton** [jeffpiazza/derbynet#169] opened 2022-01-05 02:59 UTC
The timer web interface won't connect using USB to Serial converter (FTDI chip) to Best Track timer

Derby-Timer.jar detects and communicates to timer.

**Comment by jeffpiazza** [comment] 2022-01-05 12:37
Thanks for taking the time to open a bug!

Do you have any log files to share?  

Is the USB-to-serial device offered as a choice?  

Are you on Mac or Windows or something else?

Are you using Chrome or something else?

**Comment by jaeaton** [comment] 2022-01-05 13:15
The USB to serial device is a choice and is selected. The scanning process starts.

OS: Windows 11
Browser: chromium based (chrome, edge, Vivaldi)

Are there time logs for the web interface?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jeffpiazza** [comment] 2022-01-05 22:14
Logs can be captured at the server if you turn on "remote logging" from the Timer Test page.  The location of the log file should be visible next to the remote logging switch.

**Comment by jaeaton** [comment] 2022-01-05 23:26
I turned on the logging switch, and no log is generated. In the displayed log location.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jaeaton** [comment] 2022-01-06 00:15
I tested the following devices:
Moxa nPort serial device server (network)
FTDI USB to serial adapter

LineSetup4:
Both worked

TeraTerm:
Both worked

derby-timer.jar:
Both worked

Web Interface:
Neither worked

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jeffpiazza** [comment] 2022-01-06 00:43
Sorry about the logging issue -- I hadn't realized logging didn't start until after timer discovery was complete.  (Kind of missing the most important part for situations like this.)  I have a new update in place that really does log from the start.

Appreciate your patience with this.

**Comment by jaeaton** [comment] 2022-01-06 01:02
No problem. I like helping (and I like Derby Net) and I don't do a lot of programming (C# and Matlab for data collection and processing). So I hope I am helpful. If I use Git (through visual studio) would I just point UniServer at a specific directory? Do I need to build anything?

**Comment by jeffpiazza** [comment] 2022-01-06 01:10
Probably the easiest thing is to download a new copy at https://jeffpiazza.org/derbynet/builds/.  (If you're using a database that you're invested in, you can just move it from the Data subdirectory of the old installation to the new one.)

**Comment by jaeaton** [comment] 2022-01-06 01:13
Port 0 is the Moxa, Port 1 is the USB to Serial

I usually just copy the www directory (after looking to see what has changed)

**Comment by jaeaton** [comment] 2022-01-07 21:49
I was able to test my setup using:  https://hmatulis.github.io/web-serial-terminal/

Sending v on the serial port returned: eTekGadget SmartLine Timer v20.09 (B0010)

I am assuming the Regex is looking for just part of the string

**Comment by jeffpiazza** [comment] 2022-01-08 02:36
Could you attach the log file(s) you captured a couple of days ago?

Looking through the code today, I notice that, if there's a problem opening a serial port, that fact may not be presented to the user in any useful way.  I have an update I'll put tomorrow after I try a little testing in the morning.

**Comment by jaeaton** [comment] 2022-01-08 15:26
Log from today

[timer-20220108-1523-03.log](https://github.com/jeffpiazza/derbynet/files/7833454/timer-20220108-1523-03.log)

**Comment by jeffpiazza** [comment] 2022-01-08 22:42
This looks like it's not receiving any data from the serial port, but I don't really understand why it wouldn't.

Meanwhile, here are a few potential workarounds for anyone stuck with this issue.

(1) Another user told me today they had a similar issue, but were able to get the timer to work using Edge browser (on Windows) instead of Chrome.

(2) As noted in the original comment, derby-timer.jar seems to work even if the in-browser interface doesn't.

(3) If all else fails, the -legacy command line option for derby-timer.jar ( java -jar derby-timer.jar -legacy ) uses the implementation from prior years in derby-timer.jar which is very reliable.  If you find you need to use the -legacy option, please open a new bug.

**Comment by jeffpiazza** [comment] 2022-01-18 01:03
The latest release includes a lot better error reporting and logging.  I'm hopeful those changes would help identify what's going on with this bug, but as I'm unable to reproduce, I need to rely on some testing in the field.

**Comment by jaeaton** [comment] 2022-01-24 16:06
Log using latest release

[timer-20220124-1600-36.log](https://github.com/jeffpiazza/derbynet/files/7926935/timer-20220124-1600-36.log)

**Comment by jaeaton** [comment] 2022-01-25 17:06
Log from latest version
[timer-20220125-1657-30.log](https://github.com/jeffpiazza/derbynet/files/7935659/timer-20220125-1657-30.log)

**Comment by jeffpiazza** [comment] 2022-01-26 13:39
Unfortunately these aren't showing any errors, either.

I was going to say there must be some issue with the driver or the web serial API implementation, but your success with the web-serial-terminal seems to disprove that.  web-serial-terminal is using transform streams rather than stream readers, so maybe there's a clue in that difference.

**Comment by jaeaton** [comment] 2022-01-30 19:05
Log using the latest version.
[timer-20220130-1855-07.log](https://github.com/jeffpiazza/derbynet/files/7966714/timer-20220130-1855-07.log)

**Comment by jeffpiazza** [comment] 2022-02-01 02:07
The latest logs show the same story: data apparently being written out the serial port, but nothing at all coming back, and no errors being reported.  I don't expect further experiments will give similar results.

Have you tried with Opera or Edge browsers?  Both are said to support the Web Serial API.

If you're inclined, I have a slightly different experiment whose result might be interesting.

With the USB device unplugged, open the timer interface and click on the correct timer profile ("The Champ", if I understand you correctly).  Then plug in the USB device and start scanning.

If you're able, try opening the browser's javascript console, and look for any error messages.  I think I've added catches to all the places that might throw exceptions, but maybe there's something I overlooked.

(Timer detection works by opening and closing the port repeatedly, at different baud rates, and I'm curious if that opening and closing is perhaps involved.  I noticed that the serial terminal at https://hmatulis.github.io/web-serial-terminal/ doesn't actually close the serial port correctly when disconnecting -- there's an uncaught exception reported in the javascript console, and then any attempt to re-connect fails.)

Assuming that turns up nothing new, I need to put together some code for a minimal reproducing case, and then open a bug against Chrome.

**Comment by jeffpiazza** [comment] 2022-02-01 04:00
Let's not close this just yet, but the Smartline timer requires a carriage-return character to end a command, and I just noticed a bug in the in-browser code that it fails to implement that part of the profile.  

Please have a try with build 1465.

**Comment by jaeaton** [comment] 2022-02-01 04:58
Added three logs of interest. 

0435-29 is the first attempt with build 1465. Catches the serial port.
0449-04 log receives a reply from the timer but doesn't catch it. (this is on the 4th connect and disconnect)
0449-50 log shows a good connection

Of note I was not able to get results from any of my attempts.

[timer-20220201-0449-04.log](https://github.com/jeffpiazza/derbynet/files/7975945/timer-20220201-0449-04.log)
[timer-20220201-0449-50.log](https://github.com/jeffpiazza/derbynet/files/7975946/timer-20220201-0449-50.log)
[timer-20220201-0435-29.log](https://github.com/jeffpiazza/derbynet/files/7975953/timer-20220201-0435-29.log)

**Comment by jeffpiazza** [comment] 2022-02-02 01:27
That's definitely progress, although there are still unexplained behavior.

1467 adds some more debugging if you turn on the debug-io flag: should see lots of noise about exactly what string matches are failing and what they're comparing against.  

1467 also fixes a typo in a section of code that's only exercised by SmartLine/eTekGadget timers, so that might show some promise, too.

Please give 1467 a go, turning on the debug-io flag, and see what you get.

**Comment by jaeaton** [comment] 2022-02-02 02:47
Latest log using 1467 and debug-io flag set to true.

It looks like "rs" is being sent.  It also appears when triggered it is read; the response changes from 0 to 1. Should "rg" be sent after "rs" changes to 1?

[timer-20220202-0220-20.log](https://github.com/jeffpiazza/derbynet/files/7983158/timer-20220202-0220-20.log)

**Comment by jeffpiazza** [comment] 2022-02-02 04:09
1470 I think fixes the matchers for watching the gate.

In the 0220-20.log, the timer gets recognized right off.  I don't think any of the changes in 1467 would explain that, so I'm suspicious there's still a problem there.

**Comment by jaeaton** [comment] 2022-02-02 21:36
Web timer is working in build 1472.

It seems a bit slow, although it could be a difference between Timer.jar and the web interface, they timer I used previously, or my computer.

[timer-20220202-2125-37.log](https://github.com/jeffpiazza/derbynet/files/7990193/timer-20220202-2125-37.log)

**Comment by jeffpiazza** [comment] 2022-02-04 11:36
I think we can finally consider this issue fixed.  Thank you for your patience and debugging for this.

**Closed by jeffpiazza** 2022-02-04 11:36 UTC
