### ISSUE TITLE
FastTrack timer reset immediately

### ISSUE THREAD

**Issue by Blackbird714** [jeffpiazza/derbynet#124] opened 2020-02-02 19:48 UTC
We ran our Pack "Outlaw" race last night, and one behavior that I did not specifically test for or anticipate is related to the digital display on the FastTrack timer device itself.  The issue I am seeing is exactly what is described under #63 .

During race prep, I had added this parameter to the launch of my timer process:  `-x -d FastTrackDevice -delay-reset-after-race 20`

I guess I didn't notice that the parameter doesn't apply to FastTrack devices.  Is there any way to prevent immediate reset of the physical timer display?

The timer is a FastTrack Model K3 Version 1.0.  When I ran without specifying the device it detected FastTrack, that's why I was using that on the command-line.

**Comment by Blackbird714** [comment] 2020-02-02 19:51
Here is a sample log from one of the heats that was run, if that helps at all:

```
+20:21:00.493S          INT 2020-02-01_20:21:00
+20:21:54.277S          INT SET >--GATE_OPENED--> RUNNING
+20:21:54.277H                  --> message=STARTED
+20:21:54.331H                  <-- <action-response action="timer-message" message="STARTED">
  <success/>
</action-response>
+20:22:00.494S          INT 2020-02-01_20:22:00
+20:22:03.894S          <-- A=2.832! B=3.114" C=0.000  D=9.999  E=0.000  F=0.000
+20:22:03.897S          INT RUNNING >--RESULTS_RECEIVED--> IDLE
+20:22:03.898H                  --> message=FINISHED&roundid=10&heat=2&lane1=2.832&place1=1&lane2=3.114&place2=2&lane3=9.999&lane4=9.999&lane5=9.999&lane6=9.999
+20:22:04.170H                  <-- <action-response action="timer-message" heat="2" lane1="2.832" lane2="3.114" lane3="9.999" lane4="9.999" lane5="9.999" lane6="9.999" message="FINISHED" place1="1" place2="2" roundid="10">
  <success/>
  <heat-ready class="Outlaw Alpha" heat="3" lane-mask="7" round="1" roundid="7"/>
</action-response>
+20:22:04.171H                  INT Heat ready: roundid=7, heat=3
+20:22:04.171S          --> MG
+20:22:04.171S          --> MD
+20:22:04.177S          <-- MG
+20:22:04.183S          <-- ACMD
+20:22:04.187S          <-- *
+20:22:04.222S          INT DRAINED: MG
+20:22:04.222S          INT DRAINED: ACMD
+20:22:04.222S          INT DRAINED: *
+20:22:04.222S          --> ME
+20:22:04.228S          <-- ME
+20:22:04.232S          <-- *
+20:22:04.273S          INT DRAINED: ME
+20:22:04.273S          INT DRAINED: *
+20:22:04.273S          --> MF
+20:22:04.279S          <-- MF
+20:22:04.282S          <-- *
+20:22:04.324S          INT DRAINED: MF
+20:22:04.324S          INT DRAINED: *
+20:22:04.324S          INT IDLE >--PREPARE_HEAT_RECEIVED--> MARK
+20:22:04.374S          --> LR
+20:22:04.380S          <-- LR
+20:22:04.384S          <-- *
+20:22:04.425S          INT DRAINED: LR
+20:22:04.425S          INT DRAINED: *
+20:22:04.526S          --> LR
+20:22:04.532S          <-- LR
+20:22:04.535S          <-- *
+20:22:04.576S          INT DRAINED: LR
+20:22:04.576S          INT DRAINED: *
+20:22:04.677S          --> LR
+20:22:04.683S          <-- LR
+20:22:04.687S          <-- *
+20:22:04.727S          INT DRAINED: LR
+20:22:04.728S          INT DRAINED: *
+20:22:04.828S          --> LR
+20:22:04.834S          <-- LR
+20:22:04.837S          <-- *
+20:22:04.878S          INT DRAINED: LR
+20:22:04.878S          INT DRAINED: *
+20:22:04.979S          --> LR
+20:22:04.985S          <-- LR
+20:22:04.988S          <-- *
+20:22:05.029S          INT DRAINED: LR
+20:22:05.029S          INT DRAINED: *
+20:22:05.079S          INT MARK >--GATE_CLOSED--> SET

```

**Comment by joncamp** [comment] 2020-02-03 16:51
I wonder if a better solution is to not send the lane masking until the gate is closed (ie: prepped for the next race). Depending on how you run your race, it seems like that would be enough time for the results to be displayed before you start setting up for the next one.

This may also be a "looking at it the wrong way" sort of deal, in the sense that relying on the results kiosk is a better choice than relying on the timer alone.

**Comment by Blackbird714** [comment] 2020-02-03 17:10
We will have the Now Racing/Instant Replay Kiosk on a big screen.  The issue I see is that folks attention will be on the track for a while at the end of a heat.  Current state, results appear for an instant, then they are gone... so if you blink you miss it.

> I wonder if a better solution is to not send the lane masking until the gate is closed

This maybe sounds like what I want?  Is there some configuration or parameter on the timer that lets me do this or does it require a patch?  I noticed when we were in "Not Racing" mode the results stayed on the physical timer display the way we expect/want.  It takes a manual reset of the timer gate to zero out the results.  I think I would prefer that at as option, as it could prevent some errant race results if someone accidentally breaks the beam or jostled the sensor while positioning cars for the next heat, triggering the gate release signal (which happened a few times during the Outlaw race).

Could part of our problem be how the gate release works on our track?  When the release is triggered, the timer is triggered by a car breaking the laser beam, not the gate release mechanism itself.  That means that once the cars have cleared the top of the track, the beam is restored right away.  If the gate mechanism were to interrupt the beam and it stayed that way until it were physically reset for the next cars... problem solved?  Hmmmm.... let me know your thoughts on this.

**Comment by jeffpiazza** [comment] 2020-02-03 17:28
The handler for the FastTrack timer intentionally disregards the -delay-reset-after-race command line variable, for reasons that now seem utterly dubious to me.  (We use a K3 locally, and either it works slightly differently from yours, or I just deceived myself into thinking the display itself doesn't matter.)

If you'd like, you can download a modified jar file from https://jeffpiazza.org/derbynet/private/issue124/derby-timer.jar that applies the -delay-reset-after-race value (default is 10s) for FastTrack timers, as for other timers.  See if this doesn't behave more like what you're looking for.  (If you do test this jar, please comment regardless the outcome.)

**Comment by Blackbird714** [comment] 2020-02-03 18:11
Awesome; thanks Jeff!  I have already downloaded to the server, and will test it ASAP.  Unfortunately the timer hardware is on loan to another Pack for a few days, but will report back if this version works better for us.

Thanks again!

**Comment by chunter2** [comment] 2020-02-19 00:54
I was having the same issue with my FastTrack K3 as well and just assumed this commit fixed it but it doesn't seem to work for me.  Here's some info from my log file.  

```+19:19:49.536I  Started at 2020-02-18_19:19:49
+19:19:49.541I  derby-timer.jar version v5.0-1027-20200215
+19:19:49.541I  os.name = Linux
+19:19:49.541I  ===== Command Line Arguments ==========
+19:19:49.541I  -x
+19:19:49.541I  -u
+19:19:49.541I  Timer
+19:19:49.541I  http://localhost/derbynet
+19:19:49.542I  -delay-reset-after-race
+19:19:49.542I  5
+19:19:49.542I  =======================================

+19:19:53.594S          INT Trying FastTrackDevice on /dev/ttyUSB0
+19:19:53.595S          --> RV
+19:19:53.600S          <-- v\rRV
+19:19:53.642S          <-- Copyright (c) Micro Wizard 2001-2009 a
+19:19:53.672S          <-- K3 2.10  Serial Number21063
```

I have the timer with me so I can test.  It's got a laser starter and a switch starter.  With the laser as soon as the race finishes the timer display resets back to zeros and resets the laser independent of the -delay-reset-after-race parameter.  With the switch the results stay on the display until the switch is physically closed.  The -delay-reset-after-race parameter doesn't affect the timer display at all with the switch.  I ran my races yesterday with the laser starter but without the -delay-reset-after-race parameter assuming the 20s default would take but it didn't.  I just tested today with the parameter set to 5s and got the same results.  I can do more testing if needed.  

Thanks

**Comment by jeffpiazza** [comment] 2020-02-21 02:11
chunter2, I think you've exposed a problem with the command line parsing -- it's just ignoring extra arguments that follow the URL.  Try reordering the arguments to:

java -jar derby-timer.jar -x -u Timer -delay-reset-after-race 5 localhost/derbynet

**Comment by chunter2** [comment] 2020-02-21 21:53
I just tried again using the following command with the same result.  The laser gate resets immediately and the switch never resets until it's physically closed.  

 sudo derby-timer.jar -x -u Timer -delay-reset-after-race 5 http://localhost/derbynet

```+16:42:16.499I  Started at 2020-02-21_16:42:16
+16:42:16.504I  derby-timer.jar version v5.0-1027-20200215
+16:42:16.504I  os.name = Linux
+16:42:16.504I  ===== Command Line Arguments ==========
+16:42:16.504I  -x
+16:42:16.504I  -u
+16:42:16.504I  Timer
+16:42:16.504I  -delay-reset-after-race
+16:42:16.504I  5
+16:42:16.504I  http://localhost/derbynet
+16:42:16.504I  =======================================

**Comment by chunter2** [comment] 2020-02-24 11:05
@jeffpiazza Would you be able to post your K3 gates version command response?  With the help of Microwizard I upgraded mine from 4 digits to 5 but I wonder if there's something different now compared to yours.  I'm assuming yours works with the commit above?  Also, are you using a laser start gate or a switch start gate on your track?  

Thanks

**Comment by jeffpiazza** [comment] 2020-02-24 12:24
Could you post a timer log that exhibits the behavior you're describing?  I have a feeling the "LR" command may be getting sent immediately upon closing the gate, and that may be causing the timer display to clear.

**Comment by chunter2** [comment] 2020-02-24 13:04
Here's the log file.  This is with the laser gate.  I'd still be interested in knowing your setup though.  

[timer-20200224-0759.log](https://github.com/jeffpiazza/derbynet/files/4244643/timer-20200224-0759.log)

Thanks

**Comment by chunter2** [comment] 2020-02-25 15:19
I took a quick look at the code and my log file.  It looks like the -delay-reset-after-race only affects the maybeProcessPendingLaneMask() function.  I'm wondering if this function should maybe also include the LR (RESET_LASER_GATE) command too.  It looks like the LR command is sent as soon as PREPARE_HEAT_RECEIVED happens.  It also looks like the LR command is sent multiple times even though the RG command return RG1 (gate closed) after the first LR command.  Once GATE_CLOSED happens it stops.

**Comment by jeffpiazza** [comment] 2020-02-25 15:22
I think your diagnosis is exactly right.  (I'm undecided on whether maybeProcessPendingLaneMask is the right place to send the LR, though.)

I'm out of town this week and so can't do any testing for any possible fix until the weekend.

**Comment by chunter2** [comment] 2020-02-26 15:32
Just looking at the code again.  No rush on this.  Would it be easier to just wrap the RESET_LASER_GATE call in the function whileInState in FastTrackDevice.java with the same if as maybeProcessPendingLaneMaks?  Like this?  

```
      if (lastFinishTime == 0
              || System.currentTimeMillis()
              >= lastFinishTime + postRaceDisplayDurationMillis) {
        portWrapper.writeAndDrainResponse(MicroWizard.RESET_LASER_GATE, 2, 2000);
      }
      checkConnection();
```
I think lastFinishTime and postRaceDisplayDurationMillis would need to be changed to protected though.  Just a though.

**Comment by jeffpiazza** [comment] 2020-03-01 14:30
Pretty much as you suggested.  Now that I've a few minutes to play with the timer, I can confirm this works to leave the timer display showing for the desired time.

**Closed** 2020-03-01 14:39 UTC

**Comment by chunter2** [comment] 2020-03-01 21:47
Just tested this out and it works perfectly.  Thanks for the update.
