### ISSUE TITLE
Discrepancy between race schedule and results?

### ISSUE THREAD

**Issue by nauticus25** [jeffpiazza/derbynet#202] opened 2022-03-14 01:45 UTC
We just ran our PWD and I ran into an issue that I'm still scratching my head trying to figure out. 16 racers on a 3 lane track, each scheduled to run once per lane for a total of 16 heats. At the end of the round some racers had only raced twice, a couple just once, and one did not race at all, even though all three lanes were used for each of the 16 heats. I had felt like some kids were racing a lot, and that apparently was the case. I exported the results for later investigation, cleared the schedule and set up a new schedule. I checked for and saw the name of the Scout who didn't get to race the previous round, so I assumed it had been a hiccup and moved forward. At the end of this round, the same Scout had only raced once and several others were also short the 3 races they should have had.

At this point I didn't see a way to salvage the speed awards, but the kids were having a great time watching their cars go down the track so we just kept running unrecorded races for the kids who hadn't gotten as many races in. 

It's important to mention that on the whole, the event was a big success. The kiosk displays, the racer/car photos, and especially the new voting system were all huge hits. We were able to hand out quite a few design awards. So, that plus the kids having a great time just running their cars down the track lead to an overall successful day. However, I did hang onto the speed trophies since not everyone got to race equally.

Now I'm home and have poked around the results I exported from both racing groups. Strangely, both sets of results show each Scout as having successfully raced 3 heats which definitely does not match what really happened. I'm looking at the Retrospective, and I see a lot of items shaded in red with a "Discarded" message.  There are also some "Refused result" messages. I don't recall there being any major hiccups during the race on a per-heat level. We did re-run one heat due to a car jumping lanes, but not anything over multiple heats. I also don't see two distinct racing groups of 16 heats.

Any suggestions on how to troubleshoot what may have happened?

**Comment by jeffpiazza** [comment] 2022-03-14 01:51
I'd really like to see the exported database from your race.  (You may have to rename the exported XML to have a .txt suffix, then drag and drop to attach to the issue.)

**Comment by nauticus25** [comment] 2022-03-14 02:24
Right. That would have been helpful. Complete and Cleaned database snapshots both seem to be the same file size, so I'll attach the Complete snapshot.
[derbynet-20220313-222019.txt](https://github.com/jeffpiazza/derbynet/files/8241269/derbynet-20220313-222019.txt)
.

**Comment by jeffpiazza** [comment] 2022-03-14 03:12
It looks like the Partitions table entries don't map to the corresponding subgroups, which is reason for concern on its own.

Which build are (were) you running?  (It's shown on the "About" page.)  There were some fixed bugs a while ago that might account for the wrongly-set partition table values.  Tomorrow I'll try to follow the steps you did to see if I can reproduce.

As to the original problem, as you mention, the heat results look like every racer was scheduled to race 3 times, and did race 3 times.  The Standings pages seem to show each racer having raced 3 times, too.  Did the database ever show a racer not racing 3 times?  Are the reports of kids racing less coming from the kids/families themselves (and nowhere else)?

I've known some people to find the "on deck" display confusing, as it can advance from heat to heat while the "wrangler" is looking elsewhere.  Is it possible the race crew just staged the wrong cars in some of the heats?  (Not trying to disparage your race crew or doubt your reports, just trying to narrow down what's possible and what's not.)

**Comment by nauticus25** [comment] 2022-03-14 03:31
This is revision 1495, built on February 26 2022.
(aa59b89357b8e3be3dcc7e82b6031538c06e17fb)

That's a good troubleshooting step. There isn't anything in the records that shows a difference between who really ran the race and who got recorded as having run the race. The reports are purely anecdotal, but corroborated by just about everyone, including me. The Scout who did not race in the first round had a very unique looking car and I would have remembered it running the race. Several people were taking video at various points. I'll ask around and see if I might be able to see the Race Dashboard screen for a particular heat and compare that to the recorded results. I'm not sure how to check the database itself, only the exported results .xlsx or the Standings page.

For the staging area, the car wrangler was actually looking over my shoulder at the main Race Dashboard. I had meant to bring an extra screen for him to use as an on-deck kiosk, but alas. He was pretty quick pulling cars for the current heat, so it worked out ok. All that to say he wasn't looking at anything other than what cars to pull for the current heat.

Thanks!

**Comment by jeffpiazza** [comment] 2022-03-14 19:08
The issue with the Partitions table looks to have been only a minor issue with database export, and not indicative of anything in the original database.

So as far the database is concerned, the race schedule appears to have been correctly generated, and included each racer in three heats (one per lane).  Hopefully you can reconstruct some or all of the heats as they were actually raced (e.g., from camera videos) and compare to what the scheduled heats looked like.

**Comment by jeffpiazza** [comment] 2022-03-20 12:15
Not hearing more evidence to the contrary, this appears mostly to be of a usability issue leading to some race day misunderstandings.  I'm going to close this for now.

**Closed by jeffpiazza** 2022-03-20 12:15 UTC
