### ISSUE TITLE
derby-timer "Permission denied" when opening/scanning ports in Linux

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#156] opened 2021-02-28 20:07 UTC
I have derby-timer installed an a Lubuntu mini PC with autostart enabled.  It was working fine but more recently isn't able to connect to the timer.  When looking at the log, I am getting "permission denied" errors at each port it tries.  If I launch directly as root (i.e. sudo derby-timer.jar) it works as expected. If I launch from terminal without sudo, I get the same behavior. So it appears I need root access all of a sudden to access the com ports???? 

I have tried looking around on how to start an application as root but keep running into dead ends.  Not sure what I am missing and I think the current Debian instructions haven't changed so not sure why this doesn't work.  Any help would be appreciated!

Thank you

**Comment by jeffpiazza** [comment] 2021-02-28 20:22
As I understand it, access to serial ports is normally managed with group permissions (very commonly 'dialout' group), so you'd just want to be sure that the user running derby-timer.jar is a member of the relevant group.

Check the owning group ('ls -l') for the serial port device, and the group memberships of the user ('groups').  If necessary, add user to group:

usermod -a -G dialout exampleusername

For USB-based devices (i.e., all serial ports, in practice), the permissions are set by udev rules, and the udev rules seem to change a lot from release to release, from what I've seen.

Have you upgraded your OS recently?

https://www.howtogeek.com/50787/add-a-user-to-a-group-or-second-group-on-linux/

**Comment by heatvent** [comment] 2021-02-28 20:53
Thanks Jeff.  That's the strange thing.  I setup this PC to be a standalone, plug-n-play Derbynet server.  It is setup to create a wifi hotspot for other devices to join and host the server.  As far as I know, it hasn't been connected to the internet / done any updates.  It would be a USB to serial.  I also tried installing derby-timer on an Ubuntu Mate laptop and had the same issue.  So apparently whatever group is needed isn't what the user is initially setup as during install.

I tried adding the user to the dialout group, didn't change anything.  

I went into /dev and ran ls -l with and without the USB serial device attached.  There were two new files that showed up when I plugged in the device.  One was "serial" and the other was "ttyUSB0".  serial is owned by root and the group root.  ttyUSB0 is owned by root and by the dialout group.

I tried adding the user to the root group but that didn't change anything either.

Not sure if this is a solution or a workaround, but I added the following to the beginning of the derby-timer.sh script...

# ensure running as root
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi

This was based on a blog I found (https://blog.rodneyrehm.de/archives/36-Always-Run-Script-As-Root.html).  This seemed to get it working but again not sure if this is a workaound or a solution.

**Comment by jeffpiazza** [comment] 2021-03-20 00:17
What does your tty device have for permissions?

On Raspbian 10, I see:
```
$ ls -l /dev
...
crw-rw---- 1 root dialout 188,   0 Mar 19 19:44 ttyUSB0
```
and for the default `pi` user is happily a member of `dialout` group:
```
$ groups
pi adm dialout cdrom sudo audio video plugdev games users input netdev lpadmin gpio i2c spi
```

I don't have access to an Ubuntu machine anywhere convenient, so can't check what those permissions look like.

- Are you sure you successfully added your user account to `dialout`, and that `dialout` has write access to the device?

- What devices does derby-timer.jar try to access as serial ports?

**Comment by sly4** [comment] 2022-01-19 10:46
Hello. A couple of things to consider:

1. Running as root is not best practice.
2. It's sounds like /dev/ttyUSB0 is the serial port you are looking for, so dialout is the right group.
2. You need to add the user to the dialout group, but do not make it the user's primary group. Do this by running "usermod -aG dialout username". Since you are using the pi user those is probably no applicable.
3. The group change will not take effect until you restart the session. You may need to log out and back on before you see it work.
4. In my case I have an old FastTrack P2 timer and this can't be recognized automatically. I had to define both the port and the timer model in the derby-timer.jar options. If I unplug and replug the timer from the USB port, the device file may change. Because I explicitly defined the device file in the options, I have to either stop the process and update the options, or just reboot the host.

**Comment by jeffpiazza** [comment] 2022-03-15 12:31
With no updates from @heatvent in a year, I'm going to close this tentatively as "not reproducible."

**Closed by jeffpiazza** 2022-03-15 12:31 UTC
