### ISSUE TITLE
problems with scheduling a round with a 4 lane timer on a 2 lane track (only 2 lanes available for scheduling)

### ISSUE THREAD

**Issue by frewenta** [jeffpiazza/derbynet#160] opened 2021-04-08 22:13 UTC
I have a 4 lane timer with a 2 lane track. Lanes 2 and 3 for the timer coincide with the track (X-2-3-X). I picked a 4 lane track with only 2 lanes (2 and 3) available for scheduling through derbynet. I create a round with 2 cars and 5 runs per lane but end up with 20 heats where the cars seem to be still distributed over the 4 lanes i.e. all heats in the dialog box show lanes 1 and 4 empty but some show no lanes occupied (presumably the cars are still getting scheduled for the "unschedulable" lanes 1 and 4 but not shown), other heats show 1 car on track, and then others have both cars

example (according to the race dashboard):
Heat 1: L1: empty; L2: car1; L3: empty; L4: empty  
Heat 2: L1: empty; L2: car2; L3: car1; L4: empty  
Heat 3: L1: empty; L2: empty; L3: car2; L4: empty  
Heat 4: L1: empty; L2: empty; L3: empty; L4: empty  
...

**Comment by jeffpiazza** [comment] 2021-04-08 22:32
Could you send me a database, please?  Trying just now, I'm not able to reproduce.

**Comment by frewenta** [comment] 2021-04-08 22:49
I attach the downloaded complete database snapshot (as in picture) - is
this the right file?

[image: image.png]
Thanks

**Comment by jeffpiazza** [comment] 2021-04-08 22:54
Yes, complete image is the right thing.  I don't see anything actually attached on the bug report, though.  Maybe email to me directly, jeff at jeff piazza dot org?

**Comment by jeffpiazza** [comment] 2021-04-08 23:10
Ah, OK: the schedule was generated for a four-lane track, and then two lanes were masked out.  There should probably be some safeguard against this.  (The same thing would happen if the number of lanes were changed after generating a schedule.)

Easily fixed by unscheduling the round, and then re-generating the schedule now that the lane mask is in place.

**Closed by jeffpiazza** 2021-04-08 23:10 UTC
