### ISSUE TITLE
Usability issue with checking in racer and editing partitions

### ISSUE THREAD

**Issue by nirvdrum** [jeffpiazza/derbynet#192] opened 2022-02-12 05:00 UTC
The check-in racer form has the option to add a missing den via the "Edit Partitions" option. Creating a new den this way works, but upon completion, the browser redirects back to the "Racer Check-in" page rather than the in-progress form.

**Comment by jeffpiazza** [comment] 2022-02-15 12:50
Duplicate of # #186

**Closed by jeffpiazza** 2022-02-15 12:50 UTC
